"""initial schema

Revision ID: 598450438270
Revises: 
Create Date: 2026-08-06 17:22:34.253751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598450438270'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_deadline_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('new_lead', 'outreach_sent', 'replied', 'negotiating', 'commercial_locked', 'product_sent', 'content_review', 'live', 'payment_pending', 'paid', name='creator_stage'), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'advisor', name='user_role'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('posted_by', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('audience_user_ids', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('creators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('instagram_handle', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('instagram_link', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.Enum('new_lead', 'outreach_sent', 'replied', 'negotiating', 'commercial_locked', 'product_sent', 'content_review', 'live', 'payment_pending', 'paid', name='creator_stage'), nullable=False),
    sa.Column('status', sa.Enum('priority', 'active', 'review_due', 'overdue', 'ndr', 'partnership', 'none', name='creator_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_instagram_handle'), 'creators', ['instagram_handle'], unique=True)
    op.create_index(op.f('ix_creators_phone'), 'creators', ['phone'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('target_videos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collaborations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collab_code', sa.String(length=30), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('new_lead', 'replied', 'negotiating', 'commercial_locked', 'product_sent', 'product_delivered', 'first_draft', 'approved', 'live', 'dead_leads', name='collab_stage'), nullable=False),
    sa.Column('priority', sa.Enum('priority', 'active', 'review_due', 'overdue', 'ndr', 'partnership', 'none', name='creator_status'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'partial_payment', 'payment_done', name='payment_status'), nullable=False),
    sa.Column('commercial_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('creator_reply', sa.Text(), nullable=True),
    sa.Column('commercial_quoted', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('counter_quote_agent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('counter_quote_creator', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tracking_link', sa.String(length=300), nullable=True),
    sa.Column('order_id', sa.String(length=60), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborations_collab_code'), 'collaborations', ['collab_code'], unique=True)
    op.create_index(op.f('ix_collaborations_creator_id'), 'collaborations', ['creator_id'], unique=False)
    op.create_index(op.f('ix_collaborations_owner_id'), 'collaborations', ['owner_id'], unique=False)
    op.create_table('creator_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_creator_files_created_at'), 'creator_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_creator_files_creator_id'), 'creator_files', ['creator_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'done', 'overdue', name='follow_up_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follow_ups_assigned_to'), 'follow_ups', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_follow_ups_creator_id'), 'follow_ups', ['creator_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('call', 'whatsapp', 'email', 'instagram_dm', 'note', name='message_channel'), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_creator_id'), 'messages', ['creator_id'], unique=False)
    op.create_table('ownership_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_events_created_at'), 'ownership_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ownership_events_creator_id'), 'ownership_events', ['creator_id'], unique=False)
    op.create_table('product_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('weekly_target', sa.Integer(), nullable=False),
    sa.Column('monthly_target', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_product_target_user_product')
    )
    op.create_index(op.f('ix_product_targets_product_id'), 'product_targets', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_targets_user_id'), 'product_targets', ['user_id'], unique=False)
    op.create_table('stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.Enum('new_lead', 'outreach_sent', 'replied', 'negotiating', 'commercial_locked', 'product_sent', 'content_review', 'live', 'payment_pending', 'paid', name='creator_stage'), nullable=True),
    sa.Column('to_stage', sa.Enum('new_lead', 'outreach_sent', 'replied', 'negotiating', 'commercial_locked', 'product_sent', 'content_review', 'live', 'payment_pending', 'paid', name='creator_stage'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_events_created_at'), 'stage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_stage_events_creator_id'), 'stage_events', ['creator_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_code', sa.String(length=30), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('high', 'normal', name='approval_priority'), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approval_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_collaboration_id'), 'approval_requests', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_created_at'), 'approval_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_request_code'), 'approval_requests', ['request_code'], unique=True)
    op.create_index(op.f('ix_approval_requests_requested_by'), 'approval_requests', ['requested_by'], unique=False)
    op.create_table('collab_stage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('from_stage', sa.Enum('new_lead', 'replied', 'negotiating', 'commercial_locked', 'product_sent', 'product_delivered', 'first_draft', 'approved', 'live', 'dead_leads', name='collab_stage'), nullable=True),
    sa.Column('to_stage', sa.Enum('new_lead', 'replied', 'negotiating', 'commercial_locked', 'product_sent', 'product_delivered', 'first_draft', 'approved', 'live', 'dead_leads', name='collab_stage'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collab_stage_events_collaboration_id'), 'collab_stage_events', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_collab_stage_events_created_at'), 'collab_stage_events', ['created_at'], unique=False)
    op.create_table('collaboration_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_live_attributed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collaboration_id', 'product_id')
    )
    op.create_index(op.f('ix_collaboration_products_collaboration_id'), 'collaboration_products', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_collaboration_products_product_id'), 'collaboration_products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collaboration_products_product_id'), table_name='collaboration_products')
    op.drop_index(op.f('ix_collaboration_products_collaboration_id'), table_name='collaboration_products')
    op.drop_table('collaboration_products')
    op.drop_index(op.f('ix_collab_stage_events_created_at'), table_name='collab_stage_events')
    op.drop_index(op.f('ix_collab_stage_events_collaboration_id'), table_name='collab_stage_events')
    op.drop_table('collab_stage_events')
    op.drop_index(op.f('ix_approval_requests_requested_by'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_request_code'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_created_at'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_collaboration_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_stage_events_creator_id'), table_name='stage_events')
    op.drop_index(op.f('ix_stage_events_created_at'), table_name='stage_events')
    op.drop_table('stage_events')
    op.drop_index(op.f('ix_product_targets_user_id'), table_name='product_targets')
    op.drop_index(op.f('ix_product_targets_product_id'), table_name='product_targets')
    op.drop_table('product_targets')
    op.drop_index(op.f('ix_ownership_events_creator_id'), table_name='ownership_events')
    op.drop_index(op.f('ix_ownership_events_created_at'), table_name='ownership_events')
    op.drop_table('ownership_events')
    op.drop_index(op.f('ix_messages_creator_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_follow_ups_creator_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_assigned_to'), table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_creator_files_creator_id'), table_name='creator_files')
    op.drop_index(op.f('ix_creator_files_created_at'), table_name='creator_files')
    op.drop_table('creator_files')
    op.drop_index(op.f('ix_collaborations_owner_id'), table_name='collaborations')
    op.drop_index(op.f('ix_collaborations_creator_id'), table_name='collaborations')
    op.drop_index(op.f('ix_collaborations_collab_code'), table_name='collaborations')
    op.drop_table('collaborations')
    op.drop_table('products')
    op.drop_index(op.f('ix_creators_phone'), table_name='creators')
    op.drop_index(op.f('ix_creators_instagram_handle'), table_name='creators')
    op.drop_table('creators')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('stage_deadline_rules')
    # ### end Alembic commands ###
