"""add archived fields and user active status

Revision ID: 6242f5c1fc98
Revises: 598450438270
Create Date: 2026-08-12 22:50:13.325060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6242f5c1fc98'
down_revision: Union[str, None] = '598450438270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creators', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('creators', sa.Column('archive_reason', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('creators', 'archive_reason')
    op.drop_column('creators', 'archived_at')
    # ### end Alembic commands ###
